{application,
 libtest,
 [{description,"General Testing Utilities"},
  {vsn,"0.0.1"},
  {modules,
   ['libtest.collector',
    'libtest.gen_server2',
    'libtest.matchers',
    libtest]},
  {registered,[]},
  {applications,[kernel,stdlib]},
  {env,[]}]}.